### ISSUE TITLE
Qt 5.15 Share example not working

### ISSUE THREAD

**Issue by homdx** [FalsinSoft/QtAndroidTools#19]
Qt 5.15 Share example not working

abd logcat
```I zygote  : Late-enabling -Xcheck:jni
W ResourceType: No package identifier when getting name for resource number 0x00000000
W ResourceType: No package identifier when getting name for resource number 0x00000000
W System  : ClassLoader referenced unknown path:
D AccessibilityManager: AccessibilityManager status: mPackageName = com.falsinsoft.QtAndroidToolsDemo, mOptimizeEnabled = false, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
I QtCore  : Start
I Qt      : qt started
D OpenGLRenderer: HWUI GL Pipeline
I zygote  : Do partial code cache collection, code=30KB, data=24KB
I zygote  : After code cache collection, code=29KB, data=24KB
I zygote  : Increasing code cache capacity to 128KB
I zygote  : Background concurrent copying GC freed 38265(11MB) AllocSpace objects, 10(212KB) LOS objects, 88% free, 1619KB/13MB, paused 809us total 326.744ms
I zygote  : Do partial code cache collection, code=55KB, data=59KB
I zygote  : After code cache collection, code=53KB, data=58KB
I zygote  : Increasing code cache capacity to 256KB
I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@7833a97
D OpenGLRenderer: Dumper init 2 threads <0x9437f980>
D OpenGLRenderer: <com.falsinsoft.QtAndroidToolsDemo> is running.
D ViewRootImpl[QtActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
W ndroidToolsDemo: type=1400 audit(0.0:96492): avc: denied { read } for name="u:object_r:graphics_config_prop:s0" dev="tmpfs" ino=1320 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:graphics_config_prop:s0 tclass=file permissive=0
E libc    : Access denied finding property "ro.sf.lcd_density"
E InputTransport: ro.sf.lcd_density must be defined as a build property
V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{18e78a2 com.falsinsoft.QtAndroidToolsDemo/org.qtproject.qt5.android.bindings.QtActivity,ident = 0}, this = DecorView@1b6e933[QtActivity]
D Surface : Surface::allocateBuffers(this=0xa267f800)
I zygote  : android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I OpenGLRenderer: Initialized EGL, version 1.4
D OpenGLRenderer: Swap behavior 2
D OpenGLRenderer: [init] completed
D HWUIExtension: MTKProgramCache.init: enable enhancement 1
I HWUIExtension: Get disable program binary service property (0)
I HWUIExtension: Initializing program atlas...
I ProgramBinary/Service: ProgramBinaryService client side disable debugging.
I ProgramBinary/Service: ProgramBinaryService client side disable binary content debugging.
D ProgramBinary/Service: BpProgramBinaryService.getReady
D ProgramBinary/Service: zhiyin- 1 BpProgramBinaryService::getReady()
D ProgramBinary/Service: zhiyin- 2 BpProgramBinaryService::getReady()
D ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryData
I HWUIExtension: Program binary detail: Binary length is 314156, program map length is 104.
I HWUIExtension: Succeeded to mmap program binaries. File descriptor is 63, and path is /dev/ashmem.
I HWUIExtension: No need to use file discriptor anymore, close fd(63).
D HWUIExtension: Dumper init 2 threads <0xa8b7eec0>
D HWUIExtension: <com.falsinsoft.QtAndroidToolsDemo> is running.
D HWUIExtension: Initializing program cache from 0x0, size = -1
D Surface : Surface::connect(this=0xa267f800,api=1)
D GraphicBuffer: register, handle(0xa8b2b880) (w:720 h:1344 s:736 f:0x1 u:b00)
D HWUIExtension: MTKProgramCache.generateProgram: 1099511627784
D HWUIExtension: createProgram 0x0000010000000008, binary 0xa1aed242, length 13246, format 37168 within 1561ns
D HWUIExtension: MTKProgramCache.generateProgram: 0
D HWUIExtension: createProgram 0x0000000000000000, binary 0xa1ad7000, length 10736, format 37168 within 541ns
D HWUIExtension: MTKProgramCache.generateProgram: 562949953421313
D HWUIExtension: createProgram 0x0002000000000001, binary 0xa1adf31b, length 11505, format 37168 within 685ns
D GraphicBuffer: register, handle(0xa8b2bb80) (w:720 h:1344 s:736 f:0x1 u:b00)
I zygote  : Do full code cache collection, code=125KB, data=99KB
I zygote  : After code cache collection, code=111KB, data=81KB
D Surface : Surface::connect(this=0xa267f000,api=1)
D GraphicBuffer: register, handle(0x92939b40) (w:720 h:1294 s:736 f:0x1 u:b00)
D GraphicBuffer: register, handle(0xa8b2bb80) (w:720 h:1344 s:736 f:0x1 u:b00)
D GraphicBuffer: register, handle(0x9293bb80) (w:720 h:1294 s:736 f:0x1 u:b00)
D GraphicBuffer: register, handle(0x9293bb80) (w:720 h:1294 s:736 f:0x1 u:b00)
W System.err: java.lang.ClassNotFoundException: Didn't find class "com.falsinsoft.qtandroidtools.AndroidTools" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W System.err: 	at org.qtproject.qt5.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt5.android.QtNative$7.run(QtNative.java:504)
W System.err: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
W System.err: 	at java.lang.Thread.run(Thread.java:764)
W libQtAndroidToolsDemo_armeabi-v7a.so: qrc:/tools/AndroidAppPermissions.qml:25:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{18e78a2 com.falsinsoft.QtAndroidToolsDemo/org.qtproject.qt5.android.bindings.QtActivity,ident = 0}, this = DecorView@1b6e933[QtActivity]
I zygote  : Do partial code cache collection, code=117KB, data=92KB
I zygote  : After code cache collection, code=117KB, data=92KB
I zygote  : Increasing code cache capacity to 512KB
W System.err: java.lang.ClassNotFoundException: Didn't find class "com.falsinsoft.qtandroidtools.AndroidSharing" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W System.err: 	at org.qtproject.qt5.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt5.android.QtNative$7.run(QtNative.java:504)
W System.err: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
W System.err: 	at java.lang.Thread.run(Thread.java:764)
W libQtAndroidToolsDemo_armeabi-v7a.so: qrc:/tools/AndroidSharing.qml:31:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
```

**Comment by FalsinSoft** [comment]
Just copy and paste the full logcat without any additional explanation regarding the environment and the sharing action generated this log is quite useless. You have to provide an explanation of the steps you made for allow me to reproduce the problem.

**Comment by homdx** [comment]
Excuse for troubling. All are working.
Maybe cached from another version. Testing with 5.14.2 - are ok.
After remove android build dirs and rebuild with 15.0. Some warning in Share example qml are found:

W libQtAndroidToolsDemo_armeabi-v7a.so: qrc:/tools/AndroidSharing.qml:31:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

Maybe need to fix in next version?

**Comment by FalsinSoft** [comment]
Yes, I'll fix it in the next commit. It's only a warning but is correct to adapt the code to the new qml connection syntax. I'll advise here when I'll commit the fixed version.

**Comment by homdx** [comment]
> Yes, I'll fix it in the next commit. It's only a warning but is correct to adapt the code to the new qml connection syntax. I'll advise here when I'll commit the fixed version.

Thank you)
If you need or search new examples for include you this project?

1. Add example to demonstrate working with custom Java objects/ArrayList
2. Add example to show how to work with activities and handle their result
3. Add Android Service examples with Remote Objects
4. Add Android services examples
You can found this in github Qt repo: qtandroidextras and commits in branch: 5.15

**Comment by FalsinSoft** [comment]
Just committed the version with latest qml connection syntax, no more warnings.
